apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namePrefix: dev-

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: terminal-management
    spec:
      replicas: 1
  target:
    kind: Deployment
    name: terminal-management
