apiVersion: v1
kind: ConfigMap
metadata:
  name: terminal-management-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Redis": "redis-service:6379"
      },
      "TerminalConfiguration": {
        "Url": "example.com",
        "Port": 22,
        "UsernamePattern": "user{0}",
        "PasswordPattern": "pass{0}",
        "TerminalIdPrefix": "terminal-",
        "InitialTerminalCount": 40,
        "SessionTimeoutSeconds": 300,
        "OrphanedTerminalTimeoutSeconds": 30
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: terminal-management-service
spec:
  selector:
    app: terminal-management
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terminal-management
  template:
    metadata:
      labels:
        app: terminal-management
    spec:
      containers:
      - name: terminal-management
        image: terminal-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5"]
      volumes:
      - name: config-volume
        configMap:
          name: terminal-management-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
